#! /bin/sh
bspc rule -r "*"

#############
# Autostart #
#############
sxhkd -c /home/.config/sxhkd/sxhkdrc &
nm-applet &
xrdb ~/.Xresources &
# picom -b &
feh --bg-fill /home/jim/Pictures/mountain3.jpg
# launchpolybar &


############
# Monitors #
############
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
# TODO: Add the HDMI1 Version
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10


##########
# Global #
##########
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true


#########
# Theme #
#########
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config urgent_border_color "#dd2727"
