#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI2 -d I II III IV
bspc monitor eDP1 -d V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          18

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Signal desktop='^9'
